# Generated by Django 4.2.5 on 2023-09-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasicInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("money", models.IntegerField()),
                ("day", models.IntegerField()),
                ("status", models.CharField(max_length=50)),
            ],
        ),
    ]
