# Generated by Django 4.2.5 on 2023-09-25 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicinfo',
            name='rent',
            field=models.IntegerField(default=1000),
            preserve_default=False,
        ),
    ]
