# Generated by Django 4.2.5 on 2023-09-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0002_basicinfo_rent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='day',
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='money',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='rent',
            field=models.IntegerField(default=1000),
        ),
    ]
