# Generated by Django 4.2.5 on 2023-10-07 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_comment_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
