# Generated by Django 4.2.5 on 2023-09-19 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("advertisement", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="advertisement",
            name="content",
            field=models.CharField(max_length=1000),
        ),
    ]
