# Generated by Django 4.2.5 on 2023-09-21 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0002_daybook_profit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daybook',
            name='profit',
        ),
    ]
