# Generated by Django 4.2.5 on 2023-09-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0004_daybook_num_of_customer_daybook_rival_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='dish_list',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='rival_info',
            field=models.CharField(max_length=2000),
        ),
    ]
