# Generated by Django 4.2.5 on 2023-10-11 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0009_daybook_average_score_daybook_chef_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='average_score',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='chef_salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='num_of_chef',
            field=models.IntegerField(default=0),
        ),
    ]
