# Generated by Django 4.2.5 on 2023-10-17 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0010_alter_daybook_average_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daybook',
            old_name='average_score',
            new_name='dish_score',
        ),
        migrations.AddField(
            model_name='daybook',
            name='customer_score',
            field=models.FloatField(default=0),
        ),
    ]
