# Generated by Django 4.2.5 on 2023-12-26 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0011_rename_average_score_daybook_dish_score_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daybook',
            old_name='profit',
            new_name='income',
        ),
    ]
