# Generated by Django 4.2.5 on 2023-12-25 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic_info', '0003_remove_basicinfo_day_alter_basicinfo_money_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicinfo',
            name='status',
        ),
    ]
