# Generated by Django 4.2.5 on 2023-09-21 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook',
            name='profit',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
