# Generated by Django 4.2.5 on 2023-09-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0005_alter_daybook_dish_list_alter_daybook_rival_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='daybook',
            old_name='dish_list',
            new_name='dishes',
        ),
        migrations.RemoveField(
            model_name='daybook',
            name='date',
        ),
        migrations.AddField(
            model_name='daybook',
            name='expense',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='daybook',
            name='profit',
            field=models.IntegerField(default=0),
        ),
    ]
