# Generated by Django 4.2.5 on 2023-10-02 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0006_rename_dish_list_daybook_dishes_remove_daybook_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='dishes',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='rival_info',
            field=models.CharField(max_length=4000),
        ),
    ]
