# Generated by Django 4.2.5 on 2023-10-05 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0007_alter_daybook_dishes_alter_daybook_rival_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daybook',
            name='dishes',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='daybook',
            name='rival_info',
            field=models.TextField(),
        ),
    ]
