# Generated by Django 4.2.5 on 2023-10-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daybook', '0008_alter_daybook_dishes_alter_daybook_rival_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='daybook',
            name='average_score',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daybook',
            name='chef_salary',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daybook',
            name='num_of_chef',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
